In [4]:
import numpy as np
import numpy

x = numpy.random.uniform(0.0, 5.0, 250)

print(x)


[1.68502527 2.42516178 2.90939547 1.42547815 4.85505262 3.61688522
 1.39743385 3.33749752 1.28312187 4.18967846 2.92003671 0.13188131
 2.70083149 2.35537595 2.92903223 2.45866521 4.64223551 1.24033733
 1.2418185  2.49304118 2.59533889 0.67778824 0.84768235 3.44056556
 2.09724104 1.37062159 2.05808191 2.55073051 2.47458058 4.87581423
 3.88028266 0.43955993 2.109221   3.6827687  0.49807114 4.47635678
 4.65559751 1.83636547 1.62428792 1.88811474 3.45952909 3.25836854
 2.82711706 1.55339429 2.99102958 0.19807688 0.21813393 0.17133802
 1.47653921 4.86844227 2.05142001 3.56591298 4.82474258 3.26355133
 2.84577088 1.15289218 2.73478567 3.60595265 1.78705625 4.87620449
 4.29693397 4.45622224 1.29869929 3.55089124 2.04023297 0.55170433
 2.37911929 4.20043181 1.14926767 4.60621166 3.73600803 0.66084225
 4.41798872 2.87372804 3.59398617 0.8929121  3.38956758 2.59599352
 2.90002746 1.36759671 0.86370768 4.17157218 3.93651886 1.50919055
 3.87935312 3.75553818 3.95887209 4.41702028 2.66954198 0.2538

In [10]:
a = np.arange(6)
[0, 1, 2, 3, 4, 5]
print(a)



[0 1 2 3 4 5]


In [11]:
arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])

arr = np.sort(arr)[::+1]
print(arr)


[ 1  2  2  3  4  4  6  8  9 11 18]


In [12]:
x = True

if x == True:
    print('In if-clause')
else:
    print('In else-clause')

In if-clause


In [13]:
for x in range(2):
    print('In for loop body')

else:
    print('In else loop body')


def foo(): print('In function definition')


In for loop body
In for loop body
In else loop body


In [5]:
a = 2
print(type(a))  # the `type` function tells us the type of a value

a = 1.5
print(type(a))

a = 'hello'
print(type(a))
print(type(2), type(1.5), type('hello'))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'int'> <class 'float'> <class 'str'>


In [15]:

print((
    1,
    500,
    -123456789,
    6598293784982739874982734
))

print((
    1 + 2,
    1 - 2,
    2 * 3,
    2 * 3 + 2 * 4,
    2 / 5,
    2 ** 100,  # exponentiation
    abs(-25)
))

x = 10
y = 20
z = 30
print((
    0 <= x < 100,
    0 <= x and x < 100,
    x < y < z < 40,
    x < y and y < z and z < 40,
    x < z > y,
    x < z and z > y,
))


(1, 500, -123456789, 6598293784982739874982734)
(3, -1, 6, 14, 0.4, 1267650600228229401496703205376, 25)
(True, True, True, True, True, True)


In [8]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
#Get Dimension
b.ndim

2

In [10]:
#Get Shape
b.shape

(2, 3)

In [11]:
#get type
b.dtype

dtype('float64')

In [12]:
#get size
b.itemsize

8

In [13]:
#get total size
b.size*b.itemsize

b.nbytes #shorthand

48

In [14]:
arr2 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr2)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
#Get a specific element [row,column]
arr2[1,5]
arr2[1,-2]

20

In [16]:
#Get a specifi row
arr2[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
#Get a specific column
arr2[: ,1]

array([2, 9])

In [18]:
#Getting a little more fancy [startindex:endindex:stepindex]
arr2[0,1:6:2]
arr2[0,1:-1:2]

array([2, 4, 6])

In [19]:
arr2[1,5]=20
print(arr2)

arr2[:,2]=5
print(arr2)

arr2[:,2]=[1,2]
print(arr2)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
